# Site settings
title: Wilson's
email: moiz@moiz.org
description: > # this means to ignore newlines until "baseurl:"
  A new Tea house in Bushwick, Brooklyn, NY.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wilsonstea.com" # the base hostname & protocol for your site
twitter_username: wilsonstea

# Build settings
markdown: kramdown
